### ISSUE TITLE
Getting an error when running the convo server on my VPS

### ISSUE THREAD

**Issue by Chathuranga-Jayasekara** [cxnturi0n/convoC2#3]
Im getting below error when I was running and type the " ? " and hit enter on the convo VPS server in cloud.
I tested that on the local kali instance and getting the same error.. can someone help to resolve that issue ?

goroutine 1 [running]:
runtime/debug.Stack()
        /home/centuri0n/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /home/centuri0n/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc000018280)
        /home/centuri0n/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:705 +0x91
panic({0x75fa40?, 0xc0000c4870?})
        /home/centuri0n/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/cxnturi0n/convoC2/pkg/server/tui.model.Update({0x0, {0xaeabe0, 0x0, 0x0}, {0x1, 0x1, 0x0, 0x1, 0x1, 0x0, ...}, ...}, ...)
        /home/centuri0n/convoC2/pkg/server/tui/tui.go:45 +0x6f0
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000018280, {0x845678?, 0xc000160008?}, 0xc00013e6c0)
        /home/centuri0n/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:461 +0x810
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000018280)
        /home/centuri0n/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:595 +0xaad
main.main()
        /home/centuri0n/convoC2/cmd/server/main.go:32 +0xf9

**Comment by cxnturi0n** [comment]
Hello, I tried running it again, but I didn't encounter any issues.  
Could you please provide your configuration so I can try to replicate it?

**Comment by Chathuranga-Jayasekara** [comment]
Im using Oracle cloud Ubuntu 22.04 server.
I cloned the files as mentioned in the github.
That server has open to http and https ports from any IPs.
Also installed the Golang.

I have running the  client on my Windows 10VM and I have use the below command.

convoC2_agent.exe -w "https://prod-05.australiasoutheast.logic.azure.com:443/workflows/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -t 0 -s http://15x.xxx.xxx.218/ -v

What sort of other details you want to ?

**Comment by minhnq1618** [comment]
i got the same issue here, i think it is because of this line

https://github.com/cxnturi0n/convoC2/blob/main/pkg/server/tui/tui.go#L45

what happen is when we press "enter" it is looking for the agent but there was none hence the runtime error was "runtime error: index out of range [0] with length 0"

Here is my full runtime error output

```bash
sudo ./convoC2_server_amd64 
Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/lib/go-1.22/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/usr/lib/go-1.22/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc0000de500)
	/home/minh/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:705 +0x91
panic({0x75fb00?, 0xc0000c2510?})
	/usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
github.com/cxnturi0n/convoC2/pkg/server/tui.model.Update({0x0, {0xae1c60, 0x0, 0x0}, {0x1, 0x1, 0x0, 0x1, 0x1, 0x0, ...}, ...}, ...)
	/home/minh/rteam/c2/convoC2/convoC2/pkg/server/tui/tui.go:45 +0x6f0
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0000de500, {0x845778?, 0xc000152008?}, 0xc000080600)
	/home/minh/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:461 +0x810
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0000de500)
	/home/minh/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:595 +0xaad
main.main()
	/home/minh/rteam/c2/convoC2/convoC2/cmd/server/main.go:32 +0xf9
```

so basically is that for some reason the agent did not call back to my server hence that is why my server is messed up. The funny thing is that my agent say it successfully callback to the server and waiting for command ?

**Comment by cxnturi0n** [comment]
The agent will always tell that the callback is successful if webhook url returns a positive response (which will always be the case, unless MS infrastructure is down). If your VPS server cannot receive the agent connection, may be because somehow MS server cannot reach your VPS server on port 80, perhaps due to missing inbound rule. Try to see if you can reach your VPS server on port 80 from your host.

> i got the same issue here, i think it is because of this line
> 
> https://github.com/cxnturi0n/convoC2/blob/main/pkg/server/tui/tui.go#L45
> 
> what happen is when we press "enter" it is looking for the agent but there was none hence the runtime error was "runtime error: index out of range [0] with length 0"
> 
> Here is my full runtime error output
> 
> ```shell
> sudo ./convoC2_server_amd64 
> Caught panic:
> 
> runtime error: index out of range [0] with length 0
> 
> Restoring terminal...
> 
> goroutine 1 [running]:
> runtime/debug.Stack()
> 	/usr/lib/go-1.22/src/runtime/debug/stack.go:24 +0x5e
> runtime/debug.PrintStack()
> 	/usr/lib/go-1.22/src/runtime/debug/stack.go:16 +0x13
> github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc0000de500)
> 	/home/minh/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:705 +0x91
> panic({0x75fb00?, 0xc0000c2510?})
> 	/usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
> github.com/cxnturi0n/convoC2/pkg/server/tui.model.Update({0x0, {0xae1c60, 0x0, 0x0}, {0x1, 0x1, 0x0, 0x1, 0x1, 0x0, ...}, ...}, ...)
> 	/home/minh/rteam/c2/convoC2/convoC2/pkg/server/tui/tui.go:45 +0x6f0
> github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0000de500, {0x845778?, 0xc000152008?}, 0xc000080600)
> 	/home/minh/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:461 +0x810
> github.com/charmbracelet/bubbletea.(*Program).Run(0xc0000de500)
> 	/home/minh/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:595 +0xaad
> main.main()
> 	/home/minh/rteam/c2/convoC2/convoC2/cmd/server/main.go:32 +0xf9
> ```
> 
> so basically is that for some reason the agent did not call back to my server hence that is why my server is messed up. The funny thing is that my agent say it successfully callback to the server and waiting for command ?

**Comment by cxnturi0n** [comment]
> Im using Oracle cloud Ubuntu 22.04 server. I cloned the files as mentioned in the github. That server has open to http and https ports from any IPs. Also installed the Golang.
> 
> I have running the client on my Windows 10VM and I have use the below command.
> 
> convoC2_agent.exe -w "https://prod-05.xxxxxxxxx.logic.azure.com:443/workflows/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -t 0 -s http://15x.xxx.xxx.218/ -v
> 
> After running the server on my cloud server and when I press enter, Im encounting the error above and when I type the " ? " and hit enter and then also I encountered the error.
> 
> What sort of other details you want to ?

Sorry for the late reply, new year holiday stuff.. Did you receive the agent connection before pressing enter?

**Comment by cxnturi0n** [comment]
The issue has been fixed in the latest commit. The crash originated from an index out of range error on https://github.com/cxnturi0n/convoC2/blob/main/pkg/server/tui/tui.go#L45, as pointed out by @minhnq1618.
